# Generated by Django 6.0.7 on 2026-07-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rango', models.CharField(max_length=50, unique=True)),
                ('karma_minimo', models.IntegerField()),
            ],
            options={
                'db_table': 'rangos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microsoft_id', models.CharField(max_length=255, unique=True)),
                ('correo_institucional', models.EmailField(blank=True, max_length=150, null=True)),
                ('pseudonimo', models.CharField(max_length=50, unique=True)),
                ('karma_acumulado', models.IntegerField(default=0)),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('moderador', 'Moderador'), ('administrador', 'Administrador')], default='estudiante', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
