# Generated by Django 6.0.8 on 2026-08-16 20:23

import apps.content.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_recurso_archivo_alter_recurso_tipo_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, storage=apps.content.storage.RecursoRawMediaStorage(), upload_to='recursos/%Y/%m/'),
        ),
    ]
