# Generated by Django 6.0.7 on 2026-09-14 13:43

import apps.content.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_recurso_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, storage=apps.content.storage.SupabaseS3Storage(), upload_to='recursos/%Y/%m/'),
        ),
    ]
