# Generated by Django 6.0.7 on 2026-07-29 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anio_semestre', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('materia', models.ForeignKey(db_column='materia_id', on_delete=django.db.models.deletion.RESTRICT, related_name='colecciones', to='institution.materia')),
                ('profesor', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.RESTRICT, related_name='colecciones', to='institution.profesor')),
            ],
            options={
                'db_table': 'colecciones',
                'ordering': ['-anio_semestre', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('categoria', models.CharField(choices=[('nota', 'Nota'), ('prueba', 'Prueba'), ('proyecto', 'Proyecto')], max_length=20)),
                ('tipo_recurso', models.CharField(choices=[('pdf', 'Pdf'), ('link', 'Link')], default='pdf', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('consejo_estudio', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('coleccion', models.ForeignKey(blank=True, db_column='coleccion_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='content.coleccion')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='accounts.usuario')),
            ],
            options={
                'db_table': 'recursos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
