# Generated by Django 6.0.7 on 2026-08-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='recursos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo_recurso',
            field=models.CharField(choices=[('pdf', 'Pdf'), ('zip', 'Zip'), ('link', 'Link')], default='pdf', max_length=20),
        ),
    ]
