# Generated by Django 6.0.7 on 2026-07-29 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'facultades',
                'db_table': 'facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profesores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('facultad', models.ForeignKey(db_column='facultad_id', on_delete=django.db.models.deletion.RESTRICT, related_name='carreras', to='institution.facultad')),
            ],
            options={
                'db_table': 'carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(db_column='carrera_id', on_delete=django.db.models.deletion.RESTRICT, related_name='materias', to='institution.carrera')),
            ],
            options={
                'db_table': 'materias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MateriaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(db_column='materia_id', on_delete=django.db.models.deletion.RESTRICT, to='institution.materia')),
                ('profesor', models.ForeignKey(db_column='profesor_id', on_delete=django.db.models.deletion.RESTRICT, to='institution.profesor')),
            ],
            options={
                'verbose_name_plural': 'materias_profesores',
                'db_table': 'materias_profesores',
                'unique_together': {('materia', 'profesor')},
            },
        ),
    ]
