# Generated by Django 6.0.7 on 2026-07-29 23:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonimo_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('anonimo_correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('motivo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendido', 'Atendido'), ('desestimado', 'Desestimado')], default='pendiente', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(db_column='recurso_id', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='content.recurso')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='accounts.usuario')),
            ],
            options={
                'db_table': 'reportes_recursos',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='Guardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.ForeignKey(db_column='recurso_id', on_delete=django.db.models.deletion.CASCADE, related_name='guardados', to='content.recurso')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='guardados', to='accounts.usuario')),
            ],
            options={
                'db_table': 'guardados',
                'unique_together': {('usuario', 'recurso')},
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('recurso', models.ForeignKey(db_column='recurso_id', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='content.recurso')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='accounts.usuario')),
            ],
            options={
                'db_table': 'valoraciones',
                'unique_together': {('usuario', 'recurso')},
            },
        ),
    ]
